import type { MetadataRoute } from "next"

/*  Web app manifest — the storefront's installed-to-home-screen identity (024 FR-008/FR-018).

    This replaced a static manifest.json for two reasons. It is typed, so a wrong field is a build
    error rather than a silently-ignored key; and it sits with the rest of this app's metadata
    instead of being a loose asset nobody remembers to update.

    Two things here were wrong before and are worth not re-breaking:

    1. theme_color / background_color were both #ffffff — placeholder values from an icon generator,
       not Effy's. theme_color tints the browser/OS chrome around an installed app, so a placeholder
       here is visible brand damage on every install.

    2. The icons declared ONLY purpose "maskable". A maskable icon is drawn with deliberate padding
       so a launcher can crop it to any shape; used where an unmasked icon is expected, it renders
       visibly small and over-padded. Declaring both purposes — from two DIFFERENT compositions —
       lets each context pick the right artwork.

    Icons are generated by @effy/brand. Do not hand-edit the referenced files.                     */

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Effy Shopping",
    short_name: "Effy",
    description: "Shop fresh groceries and everyday essentials from Effy, delivered to your door.",
    start_url: "/",
    display: "standalone",
    // The monochrome accent (constitution Principle V, v1.11.0). There is no brand hue: near-black
    // is the accent on light appearance, which is what a browser chrome/theme colour should reflect.
    theme_color: "#1A1A1A",
    // Matches the design system's light ground (--background), so the PWA splash does not flash a
    // different white before the app paints.
    background_color: "#FFFFFF",
    icons: [
      { src: "/web-app-icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/web-app-icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/web-app-manifest-192x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/web-app-manifest-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  }
}
