#!/usr/bin/env node
// GENERATOR — the ONLY writer of packages/email-kit/src/generated/ and dist/.
//
// One pass produces every derived artifact, so they cannot disagree with each other:
//
//   packages/design-system/src/tokens.css   (the brand SSOT)
//        │
//        ├─→ src/generated/tokens.generated.ts   the palette, as literal hex, for TS consumers
//        ├─→ src/generated/theme.mjml            the head fragment every template includes
//        │
//   src/templates/<id>.mjml ──MJML──→ dist/<id>.html        review + lint artifact
//   src/text/<id>.txt.hbs   ──copy──→ dist/<id>.txt         review + lint artifact
//                                     dist/templates.generated.ts   ← what the BUNDLER sees
//                                     dist/manifest.json
//
// ⚠ WHY TWO ARTIFACTS PER TEMPLATE: esbuild bundles JavaScript, not .html. A readable .html file is
// what makes a design change reviewable in a diff; a TS module is what makes it bundler-agnostic and
// testable. Both are written by THIS pass and byte-compared by check-email.mjs, so the duplication
// cannot drift. (A .html esbuild loader was rejected: it needs identical, correct configuration in
// three serverless.yml files, and a wrong one fails at runtime — 035's failure mode exactly.)
//
// ⚠ NO MINIFICATION. Minifying MJML output with a web-oriented minifier breaks email clients
// (Artsy, in production). The size budget is met by authoring less, not by compressing.
//
// ⚠ {{handlebars}} and Cognito's {####} pass through MJML untouched, by design (the thoughtbot
// pattern): the artifact ships with its placeholders intact for runtime substitution.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, resolve, basename } from "node:path";
import mjml2html from "mjml";

import { buildEmailTokens, validateEmailTokens, TYPE, LAYOUT } from "./lib/tokens.mjs";
import { buildThemeMjml } from "./lib/theme.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(here, "..");
const SRC = resolve(PKG, "src");
const GENERATED = resolve(SRC, "generated");
const TEMPLATES = resolve(SRC, "templates");
const TEXT = resolve(SRC, "text");
const DIST = resolve(PKG, "dist");

const BANNER = "// GENERATED by scripts/gen-email.mjs — DO NOT EDIT. Run `make email-gen`.\n";

function sha256(s) {
  return createHash("sha256").update(s, "utf8").digest("hex").slice(0, 16);
}

/** Emit the palette as literal hex for TypeScript consumers. ⚠ No `var()` may reach email output. */
function emitTokensTs(tokens) {
  const lines = [
    BANNER,
    "// Source of truth: packages/design-system/src/tokens.css.",
    "// ⚠ CSS custom properties are unsupported in Gmail (every platform), every Word-engine Outlook,",
    "// Outlook.com, Outlook mobile, Yahoo and AOL — essentially the whole audience. So the variables",
    "// live in the generator and only literal values reach a message.",
    "",
    "export const EMAIL_TOKENS = {",
    `  light: ${JSON.stringify(tokens.light, null, 4).replace(/\n/g, "\n  ")},`,
    `  dark: ${JSON.stringify(tokens.dark, null, 4).replace(/\n/g, "\n  ")},`,
    `  radiusSm: ${JSON.stringify(tokens.radiusSm)},`,
    "} as const;",
    "",
    `export const EMAIL_TYPE = ${JSON.stringify(TYPE, null, 2)} as const;`,
    "",
    `export const EMAIL_LAYOUT = ${JSON.stringify(LAYOUT, null, 2)} as const;`,
    "",
    "export type EmailTokenRole = keyof typeof EMAIL_TOKENS.light;",
    "",
  ];
  writeFileSync(resolve(GENERATED, "tokens.generated.ts"), lines.join("\n"));
}

/** Compile one template. Returns the rendered HTML with placeholders intact. */
function compile(filePath) {
  const src = readFileSync(filePath, "utf8");
  const { html, errors } = mjml2html(src, {
    filePath,
    validationLevel: "strict",
    // ⚠ FALSE, and this is a correctness fix, not an optimisation. With comments kept, every
    // explanatory note in the .mjml source — including the reasoning about phishing primitives and
    // account takeover — was being SHIPPED INSIDE CUSTOMER EMAIL, where anyone can read the source.
    // It also cost ~2 KB against Cognito's ~20,000-character limit.
    // ⚠ MSO conditionals are NOT affected: the ghost tables are GENERATED by MJML (not source
    // comments), and our own `<!--[if mso]>` font override lives in mj-raw, which is passed through
    // verbatim. A check below asserts both survive, because "should survive" is not evidence.
    keepComments: false,
    minify: false,
    // ⚠ NO AUTOMATIC FONT IMPORTS. MJML ships a default font map and injects a Google Fonts <link>
    // AND an @import for any family in that map it finds in a font-family — and our fallback stack
    // names Roboto. Every message was therefore carrying a request to fonts.googleapis.com:
    //   · an uninvited third-party dependency on the platform's most sensitive mail,
    //   · a privacy leak — Google learns when a recipient opens a sign-in code,
    //   · dead weight, since Gmail and Outlook ignore @font-face anyway, and
    //   · an @import rule one nesting mistake away from making Gmail discard the whole style block.
    // The platform deliberately ships no web font at all (see theme.mjs); this makes that true.
    fonts: {},
  });
  if (errors && errors.length) {
    const detail = errors.map((e) => `      ${e.formattedMessage ?? e.message}`).join("\n");
    throw new Error(`MJML refused ${basename(filePath)}:\n${detail}`);
  }
  return promoteHeading(html, basename(filePath));
}

/**
 * ⚠ MJML RENDERS EVERY mj-text AS A <div>, INCLUDING HEADINGS — so a message built from mj-text
 * alone has no semantic heading at all, and a screen reader announces one undifferentiated run of
 * text (spec FR-030).
 *
 * The obvious fix — authoring a raw <h1> inside mj-text — is worse: an <h1> needs its own inline
 * margin, size, weight and colour or the Word engine applies its own defaults, which would put
 * literal font sizes back into templates and break the rule that a template writes no size (FR-016).
 * `font-size: inherit` is not a safe answer either; it is unreliable in the Word engine.
 *
 * So the generator rewrites it instead: the div carrying `e-h1` becomes an <h1> with the SAME inline
 * style plus `margin:0`. Semantics for a screen reader, byte-identical appearance, and templates
 * stay free of sizes.
 */
function promoteHeading(html, label) {
  // ⚠ MJML puts css-class on the <td>; the styled element is the <div> INSIDE it. Match the cell,
  // then promote its first child div. (Reading the compiled output, not assuming its shape, is what
  // caught this — the first version of this function matched `<div class="e-h1">`, which MJML never
  // emits, so it silently did nothing and every message shipped with no heading at all.)
  const cell = /<td([^>]*\bclass="[^"]*\be-h1\b[^"]*"[^>]*)>([\s\S]*?)<\/td>/;
  const m = html.match(cell);
  if (!m) return html; // Not every message needs a heading.

  // ⚠ Exactly one heading per message; a second is a heading-order defect (spec FR-030). Counted
  // BEFORE promotion — the cell keeps its class afterwards, so counting after always finds one.
  const headingCells = html.match(new RegExp(cell.source, "g")) ?? [];
  if (headingCells.length > 1) {
    throw new Error(
      `${label}: ${headingCells.length} e-h1 headings — a message has exactly one <h1>`,
    );
  }

  const inner = m[2];
  const divRe = /<div(\s[^>]*)?>([\s\S]*?)<\/div>/;
  const dm = inner.match(divRe);
  if (!dm) {
    throw new Error(`${label}: an e-h1 cell contains no styled element to promote`);
  }
  const attrs = dm[1] ?? "";
  const promotedAttrs = /style="/.test(attrs)
    ? attrs.replace(/style="/, 'style="margin:0;')
    : `${attrs} style="margin:0;"`;
  const promotedInner = inner.replace(divRe, `<h1${promotedAttrs}>${dm[2]}</h1>`);
  const out = html.replace(cell, `<td${m[1]}>${promotedInner}</td>`);

  return out;
}

function main() {
  // 1 — tokens, derived and validated before anything is written.
  const tokens = buildEmailTokens();
  const tokenErrors = validateEmailTokens(tokens);
  if (tokenErrors.length) {
    console.error("✗ email tokens are invalid:\n  - " + tokenErrors.join("\n  - "));
    process.exit(1);
  }

  mkdirSync(GENERATED, { recursive: true });
  emitTokensTs(tokens);
  writeFileSync(resolve(GENERATED, "theme.mjml"), buildThemeMjml(tokens));

  // 2 — every template.
  if (!existsSync(TEMPLATES)) {
    console.error(`✗ no templates directory at ${TEMPLATES}`);
    process.exit(1);
  }
  const ids = readdirSync(TEMPLATES)
    .filter((f) => f.endsWith(".mjml"))
    .map((f) => f.replace(/\.mjml$/, ""))
    .sort();

  if (!ids.length) {
    console.error("✗ no templates found — nothing to generate");
    process.exit(1);
  }

  // ⚠ Wipe only the artifacts we own; dist/preview/ is a build output and is left alone.
  for (const f of existsSync(DIST) ? readdirSync(DIST) : []) {
    if (f.endsWith(".html") || f.endsWith(".txt") || f === "manifest.json" || f === "templates.generated.ts") {
      rmSync(resolve(DIST, f));
    }
  }
  mkdirSync(DIST, { recursive: true });

  const manifest = {};
  const bundle = {};

  for (const id of ids) {
    const html = compile(resolve(TEMPLATES, `${id}.mjml`));

    const textPath = resolve(TEXT, `${id}.txt.hbs`);
    if (!existsSync(textPath)) {
      // ⚠ Not a warning. HTML-only mail trips SpamAssassin's MIME_HTML_ONLY, and several Android
      // clients take the inbox preview line from the text part.
      console.error(`✗ ${id}: no plain-text part at src/text/${id}.txt.hbs`);
      process.exit(1);
    }
    const text = readFileSync(textPath, "utf8");

    writeFileSync(resolve(DIST, `${id}.html`), html);
    writeFileSync(resolve(DIST, `${id}.txt`), text);

    bundle[id] = { html, text };
    manifest[id] = {
      htmlBytes: Buffer.byteLength(html, "utf8"),
      htmlChars: [...html].length,
      textBytes: Buffer.byteLength(text, "utf8"),
      htmlSha: sha256(html),
      textSha: sha256(text),
    };
  }

  // 3 — the runtime artifact. JSON.stringify escapes everything; the bundler sees plain strings.
  const bundleLines = [
    BANNER,
    "// ⚠ This is what the LAMBDA BUNDLER sees. The matching dist/<id>.html files are the review and",
    "// lint artifacts; check-email.mjs asserts the two carry byte-identical content.",
    "",
    "export interface CompiledTemplate {",
    "  readonly html: string;",
    "  readonly text: string;",
    "}",
    "",
    "export const COMPILED_TEMPLATES: Readonly<Record<string, CompiledTemplate>> = {",
    ...ids.map((id) => `  ${JSON.stringify(id)}: {\n    html: ${JSON.stringify(bundle[id].html)},\n    text: ${JSON.stringify(bundle[id].text)},\n  },`),
    "};",
    "",
  ];
  writeFileSync(resolve(DIST, "templates.generated.ts"), bundleLines.join("\n"));
  writeFileSync(resolve(DIST, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

  console.log(`✓ email-gen — ${ids.length} template(s)`);
  for (const id of ids) {
    const m = manifest[id];
    console.log(`    ${id.padEnd(32)} ${String(m.htmlBytes).padStart(6)} B html · ${String(m.textBytes).padStart(5)} B text`);
  }
}

main();
