// GENERATED by packages/design-system/scripts/gen-stripe-appearance.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/design-system/src/tokens.css. Run `pnpm --filter @effy/design-system tokens:gen`.
// Guarded by tokens:check — a hand edit here fails the build and names this file.

/**
 * The payment provider's Appearance, derived from the Effy design tokens (051 FR-029/FR-030).
 *
 * Two appearances, because the platform's accent INVERTS: near-black on light, near-white on dark.
 * Pick with the shopper's live appearance setting and re-create the Elements group when it changes —
 * the provider reads appearance at creation time and does not re-theme in place.
 */
export type StripeAppearance = {
  theme: "stripe";
  variables: Record<string, string>;
  rules: Record<string, Record<string, string>>;
};

export const paymentAppearanceLight: StripeAppearance = {
  theme: "stripe",
  variables: {
      "colorPrimary": "#1d4ed8",
      "colorBackground": "#ffffff",
      "colorText": "#0b1220",
      "colorTextSecondary": "#5c6b86",
      "colorTextPlaceholder": "#5c6b86",
      "colorDanger": "#cf2b1f",
      "colorIcon": "#5c6b86",
      "borderRadius": "6px",
      "fontFamily": "\"General Sans\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSizeBase": "16px",
      "spacingUnit": "4px"
  },
  rules: {
      ".Input": {
          "border": "1px solid #d7e0ee",
          "borderRadius": "9999px",
          "padding": "10px 16px",
          "boxShadow": "none"
      },
      ".Input:focus": {
          "border": "1px solid #7993ca",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Input--invalid": {
          "border": "1px solid #cf2b1f",
          "boxShadow": "none"
      },
      ".Label": {
          "fontWeight": "500",
          "fontSize": "13px",
          "color": "#0b1220"
      },
      ".Tab, .Block": {
          "border": "1px solid #e1e8f3",
          "borderRadius": "6px",
          "boxShadow": "none"
      },
      ".Tab:focus, .Tab--selected": {
          "border": "1px solid #0b1220",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Error": {
          "color": "#cf2b1f",
          "fontSize": "13px"
      }
  },
};

export const paymentAppearanceDark: StripeAppearance = {
  theme: "stripe",
  variables: {
      "colorPrimary": "#60a5fa",
      "colorBackground": "#262626",
      "colorText": "#fafafa",
      "colorTextSecondary": "#adadad",
      "colorTextPlaceholder": "#adadad",
      "colorDanger": "#f87171",
      "colorIcon": "#adadad",
      "borderRadius": "6px",
      "fontFamily": "\"General Sans\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSizeBase": "16px",
      "spacingUnit": "4px"
  },
  rules: {
      ".Input": {
          "border": "1px solid #525252",
          "borderRadius": "9999px",
          "padding": "10px 16px",
          "boxShadow": "none"
      },
      ".Input:focus": {
          "border": "1px solid #737373",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Input--invalid": {
          "border": "1px solid #f87171",
          "boxShadow": "none"
      },
      ".Label": {
          "fontWeight": "500",
          "fontSize": "13px",
          "color": "#fafafa"
      },
      ".Tab, .Block": {
          "border": "1px solid #404040",
          "borderRadius": "6px",
          "boxShadow": "none"
      },
      ".Tab:focus, .Tab--selected": {
          "border": "1px solid #fafafa",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Error": {
          "color": "#f87171",
          "fontSize": "13px"
      }
  },
};

/** Resolve the appearance for a rendered mode. */
export function paymentAppearance(mode: "light" | "dark"): StripeAppearance {
  return mode === "dark" ? paymentAppearanceDark : paymentAppearanceLight;
}
