// GENERATED by packages/design-system/scripts/gen-stripe-appearance.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/design-system/src/tokens.css. Run `pnpm --filter @effy/design-system tokens:gen`.
// Guarded by tokens:check — a hand edit here fails the build and names this file.

/**
 * The payment provider's Appearance, derived from the Effy design tokens (051 FR-029/FR-030).
 *
 * Two appearances, because the platform's accent INVERTS: near-black on light, near-white on dark.
 * Pick with the shopper's live appearance setting and re-create the Elements group when it changes —
 * the provider reads appearance at creation time and does not re-theme in place.
 */
export type StripeAppearance = {
  theme: "stripe";
  variables: Record<string, string>;
  rules: Record<string, Record<string, string>>;
};

export const paymentAppearanceLight: StripeAppearance = {
  theme: "stripe",
  variables: {
      "colorPrimary": "#171717",
      "colorBackground": "#ffffff",
      "colorText": "#0a0a0a",
      "colorTextSecondary": "#525252",
      "colorTextPlaceholder": "#808080",
      "colorDanger": "#e01010",
      "colorIcon": "#525252",
      "borderRadius": "8px",
      "fontFamily": "\"General Sans\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSizeBase": "16px",
      "spacingUnit": "4px"
  },
  rules: {
      ".Input": {
          "border": "1px solid #e5e5e5",
          "borderRadius": "9999px",
          "padding": "10px 16px",
          "boxShadow": "none"
      },
      ".Input:focus": {
          "border": "1px solid #808080",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Input--invalid": {
          "border": "1px solid #e01010",
          "boxShadow": "none"
      },
      ".Label": {
          "fontWeight": "500",
          "fontSize": "13px",
          "color": "#0a0a0a"
      },
      ".Tab, .Block": {
          "border": "1px solid #e5e5e5",
          "borderRadius": "8px",
          "boxShadow": "none"
      },
      ".Tab:focus, .Tab--selected": {
          "border": "1px solid #0a0a0a",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Error": {
          "color": "#e01010",
          "fontSize": "13px"
      }
  },
};

export const paymentAppearanceDark: StripeAppearance = {
  theme: "stripe",
  variables: {
      "colorPrimary": "#e5e5e5",
      "colorBackground": "#171717",
      "colorText": "#fafafa",
      "colorTextSecondary": "#b5b5b5",
      "colorTextPlaceholder": "#808080",
      "colorDanger": "#ff6b6b",
      "colorIcon": "#b5b5b5",
      "borderRadius": "8px",
      "fontFamily": "\"General Sans\", ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "fontSizeBase": "16px",
      "spacingUnit": "4px"
  },
  rules: {
      ".Input": {
          "border": "1px solid #2f2f2f",
          "borderRadius": "9999px",
          "padding": "10px 16px",
          "boxShadow": "none"
      },
      ".Input:focus": {
          "border": "1px solid #737373",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Input--invalid": {
          "border": "1px solid #ff6b6b",
          "boxShadow": "none"
      },
      ".Label": {
          "fontWeight": "500",
          "fontSize": "13px",
          "color": "#fafafa"
      },
      ".Tab, .Block": {
          "border": "1px solid #232323",
          "borderRadius": "8px",
          "boxShadow": "none"
      },
      ".Tab:focus, .Tab--selected": {
          "border": "1px solid #fafafa",
          "boxShadow": "none",
          "outline": "none"
      },
      ".Error": {
          "color": "#ff6b6b",
          "fontSize": "13px"
      }
  },
};

/** Resolve the appearance for a rendered mode. */
export function paymentAppearance(mode: "light" | "dark"): StripeAppearance {
  return mode === "dark" ? paymentAppearanceDark : paymentAppearanceLight;
}
