/**
 * Shared build logic for legal:gen and legal:check, so they cannot diverge.
 * Produces the TS (web) and Kotlin (mobile) generated sources from the canonical Markdown.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const HERE = dirname(fileURLToPath(import.meta.url))
export const PKG = join(HERE, "..")
export const SRC = join(PKG, "src")
const DOCS = join(SRC, "documents")
const REPO = join(PKG, "..", "..")

export const TS_PATH = join(SRC, "generated", "documents.ts")
export const KT_PATH = join(
  REPO,
  "apps/customer-mobile/shared/src/commonMain/kotlin/com/effyshopping/customer/mobile/features/legal/generated/LegalContent.kt",
)

const identifiers = JSON.parse(readFileSync(join(SRC, "identifiers.json"), "utf8"))
const manifest = JSON.parse(readFileSync(join(SRC, "manifest.json"), "utf8"))

function parseFrontMatter(raw, where) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(raw)
  if (!m) throw new Error(`${where}: missing front matter`)
  const meta = {}
  for (const line of m[1].split("\n")) {
    const kv = /^([a-zA-Z]+):\s*(.*)$/.exec(line.trim())
    if (kv) meta[kv[1]] = kv[2].replace(/^["']|["']$/g, "")
  }
  return { meta, body: m[2].trim() }
}

function substitute(text, where) {
  return text.replace(/\{\{([a-zA-Z]+)\}\}/g, (_, key) => {
    if (!(key in identifiers)) throw new Error(`${where}: unknown identifier token {{${key}}}`)
    return identifiers[key]
  })
}

export function buildDocuments() {
  // Manifest integrity: no stray document dirs.
  const dirs = existsSync(DOCS) ? readdirSync(DOCS, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name) : []
  const slugs = new Set(manifest.map((m) => m.slug))
  for (const d of dirs) {
    if (!slugs.has(d)) throw new Error(`Document directory '${d}' is not listed in manifest.json`)
  }

  const built = []
  for (const entry of manifest) {
    const dir = join(DOCS, entry.slug)
    if (!existsSync(dir)) throw new Error(`Missing document directory for slug '${entry.slug}'`)
    const versionFiles = readdirSync(dir)
      .filter((f) => /^v\d+\.md$/.test(f))
      .sort((a, b) => parseInt(b.slice(1)) - parseInt(a.slice(1)))
    if (versionFiles.length === 0) throw new Error(`No version files (vN.md) for '${entry.slug}'`)

    const versions = versionFiles.map((f) => {
      const where = `${entry.slug}/${f}`
      const { meta, body } = parseFrontMatter(readFileSync(join(dir, f), "utf8"), where)
      for (const req of ["title", "version", "effectiveDate", "status"]) {
        if (!meta[req]) throw new Error(`${where}: front matter missing '${req}'`)
      }
      return { ...meta, body: substitute(body, where) }
    })
    const current = versions.find((v) => v.status === "current")
    if (!current) throw new Error(`${entry.slug}: no version with status: current`)

    built.push({
      slug: entry.slug,
      title: current.title,
      category: entry.category,
      order: entry.order,
      currentVersion: current.version,
      effectiveDate: current.effectiveDate,
      body: current.body,
      versions: versions.map((v) => ({ version: v.version, effectiveDate: v.effectiveDate, status: v.status, body: v.body })),
    })
  }
  built.sort((a, b) => a.order - b.order)
  return built
}

export function emitTs(built) {
  const header = `// GENERATED by scripts/gen.mjs — DO NOT EDIT. Run: pnpm --filter @effy/legal-content legal:gen\n// Canonical source: packages/legal-content/src/documents/*/v*.md\nimport type { LegalDocument } from "../types"\n\n`
  return header + `export const documents: LegalDocument[] = ${JSON.stringify(built, null, 2)}\n`
}

export function emitKotlin(built) {
  const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")
  const tq = (s) => s.replace(/"""/g, '\\"\\"\\"')
  const docs = built
    .map((d) => {
      const versions = d.versions
        .map(
          (v) =>
            `        LegalDocumentVersion(version = "${esc(v.version)}", effectiveDate = "${esc(v.effectiveDate)}", status = "${esc(v.status)}", body = """${tq(v.body)}"""),`,
        )
        .join("\n")
      return `    LegalDocument(
        slug = "${esc(d.slug)}",
        title = "${esc(d.title)}",
        category = "${esc(d.category)}",
        order = ${d.order},
        currentVersion = "${esc(d.currentVersion)}",
        effectiveDate = "${esc(d.effectiveDate)}",
        body = """${tq(d.body)}""",
        versions = listOf(
${versions}
        ),
    ),`
    })
    .join("\n")

  return `// GENERATED by packages/legal-content/scripts/gen.mjs — DO NOT EDIT.
// Canonical source: packages/legal-content/src/documents/*/v*.md
package com.effyshopping.customer.mobile.features.legal.generated

data class LegalDocumentVersion(
    val version: String,
    val effectiveDate: String,
    val status: String,
    val body: String,
)

data class LegalDocument(
    val slug: String,
    val title: String,
    val category: String,
    val order: Int,
    val currentVersion: String,
    val effectiveDate: String,
    val body: String,
    val versions: List<LegalDocumentVersion>,
)

val LEGAL_DOCUMENTS: List<LegalDocument> = listOf(
${docs}
)
`
}

export const requiredSlugs = manifest.map((m) => m.slug)
