// GENERATED by packages/design-system/scripts/gen-stripe-appearance.mjs — DO NOT EDIT BY HAND.
// Source of truth: packages/design-system/src/tokens.css. Run `pnpm --filter @effy/design-system tokens:gen`.
// Guarded by tokens:check — a hand edit here fails the build and names this file.

package com.effyshopping.customer.mobile.design.payment

import androidx.compose.ui.graphics.Color
import com.stripe.android.paymentsheet.PaymentSheet

/**
 * The payment provider's Appearance for the mobile payment element (051 FR-029/FR-030).
 *
 * ⚠ BOTH appearances are supplied. The platform's accent INVERTS between them, so a single palette
 * would be invisible in one mode (constitution Principle V). Omitting [colorsDark] would leave the
 * payment form light inside a dark app.
 *
 * ⚠ [typography] takes an ANDROID FONT RESOURCE id, not a Compose Resource. General Sans lives in
 * androidApp/src/main/res/font/ for exactly this reason — the composeResources copy has no R.font id,
 * and passing nothing here renders the payment form in the SYSTEM font beside Effy's own type, with
 * nothing failing to compile (research R8).
 */
object EffyPaymentAppearance {
    private val Light = PaymentSheet.Colors(
        primary = Color(0xFF171717.toInt()),
        surface = Color(0xFFFFFFFF.toInt()),
        component = Color(0xFFFFFFFF.toInt()),
        componentBorder = Color(0xFFE5E5E5.toInt()),
        componentDivider = Color(0xFFE5E5E5.toInt()),
        onComponent = Color(0xFF0A0A0A.toInt()),
        onSurface = Color(0xFF0A0A0A.toInt()),
        subtitle = Color(0xFF525252.toInt()),
        placeholderText = Color(0xFF808080.toInt()),
        appBarIcon = Color(0xFF525252.toInt()),
        error = Color(0xFFE01010.toInt()),
    )

    private val Dark = PaymentSheet.Colors(
        primary = Color(0xFFE5E5E5.toInt()),
        surface = Color(0xFF171717.toInt()),
        component = Color(0xFF171717.toInt()),
        componentBorder = Color(0xFF2F2F2F.toInt()),
        componentDivider = Color(0xFF232323.toInt()),
        onComponent = Color(0xFFFAFAFA.toInt()),
        onSurface = Color(0xFFFAFAFA.toInt()),
        subtitle = Color(0xFFB5B5B5.toInt()),
        placeholderText = Color(0xFF808080.toInt()),
        appBarIcon = Color(0xFFB5B5B5.toInt()),
        error = Color(0xFFFF6B6B.toInt()),
    )

    /**
     * @param generalSansFontResId the General Sans font resource. ⚠ REQUIRED, not nullable, on
     *   purpose: a null renders the payment form in the system font beside Effy's own type and nothing
     *   errors, so the type system refuses the mistake instead.
     */
    fun of(generalSansFontResId: Int): PaymentSheet.Appearance = PaymentSheet.Appearance(
        colorsLight = Light,
        colorsDark = Dark,
        shapes = PaymentSheet.Shapes(
            cornerRadiusDp = 8f,
            borderStrokeWidthDp = 1f,
        ),
        // ⚠ Typography is NOT a data class in this SDK — there is no .default.copy(...). Verified
        // against the 23.17.0 bytecode: the constructor is (sizeScaleFactor, fontResId). A .copy()
        // here does not compile, which is the good failure; the bad one would be silently accepting a
        // null fontResId, so the parameter is required rather than defaulted.
        typography = PaymentSheet.Typography(
            sizeScaleFactor = 1.0f,
            fontResId = generalSansFontResId,
        ),
        primaryButton = PaymentSheet.PrimaryButton(
            shape = PaymentSheet.PrimaryButtonShape(
                // Effy's buttons are pills everywhere on the platform.
                cornerRadiusDp = 28f,
            ),
        ),
    )
}
