import Link from "next/link"

import { cn } from "@/lib/utils"

/**
 * The Effy logo — the authored mark plus the wordmark.
 *
 * ── Why it points at `/icon.svg` rather than a copy ─────────────────────────────────────────────
 *
 * `apps/customer-web/app/icon.svg` is GENERATED by `packages/brand` from the one authored vector
 * (`packages/brand/src/logo.svg`) and is guarded by `make brand-check`, which fails the build and
 * names the surface when a committed asset drifts from the source.
 *
 * Copying the SVG into `public/` or inlining its paths here would create a second copy that the drift
 * check does not know about — so the header could keep rendering last month's mark indefinitely while
 * every checked surface stayed correct. Referencing the generated file keeps the header inside the
 * pipeline: regenerate the brand, and this updates with it.
 *
 * Next serves App Router icon file conventions at their route, so `/icon.svg` is a stable URL.
 *
 * ⚠ A plain `<img>`, not `next/image`. The optimizer refuses SVG unless `dangerouslyAllowSVG` is set,
 * and there is nothing to optimize in a 2 KB vector — raster resizing is the whole point of that
 * component. The explicit width/height prevent layout shift.
 */
export function BrandMark({
  href = "/",
  className,
  size = 28,
}: {
  /** Omit to render as a plain (non-linking) mark — e.g. inside a page that is already home. */
  href?: string | null
  className?: string
  size?: number
}) {
  const content = (
    <>
      <img
        src="/icon.svg"
        alt=""
        width={size}
        height={size}
        className="shrink-0"
        // Decorative: the wordmark beside it carries the name, so announcing both would read
        // "Effy Effy" to a screen reader.
        aria-hidden="true"
      />
      <span className="text-xl font-extrabold uppercase tracking-[-0.02em]">Effy</span>
    </>
  )

  const classes = cn("flex shrink-0 items-center gap-2", className)

  if (href === null) {
    return (
      <span className={classes} aria-label="Effy">
        {content}
      </span>
    )
  }

  return (
    <Link href={href} className={classes} aria-label="Effy home">
      {content}
    </Link>
  )
}
